### ISSUE TITLE
yarn sbができない

### ISSUE THREAD

**Issue by haruchu** [haruki00000000/haru-frontend-basic-2022-todoapp#1]

**Comment by haruchu** [comment]
# エラー文

```
Starting the development server...

/Users/xxxx/xxxx/React_Practice/my-app/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/xxxx/xxxx/React_Practice/my-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/xxxx/xxxx/React_Practice/my-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/xxxx/xxxx/React_Practice/my-app/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/xxxx/xxxx/React_Practice/my-app/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/xxxx/xxxx/React_Practice/my-app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/xxxx/xxxx/React_Practice/my-app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/xxxx/xxxx/React_Practice/my-app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/xxxx/xxxx/React_Practice/my-app/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
```

**Comment by haruchu** [comment]
# 対処法
Node.jsのバージョンを下げる。
推奨版(v16.13.0)に切り替えて再度npm startしたら無事に開発サーバーが起動。
